---
- name: 간단한 웹 서버 구축
  hosts: all
  gather_facts: false
  tasks:
    - name: 패키지 삭제
      ansible.builtin.dnf:
        name: httpd
        state:  absent
        
    - name: 파일 삭제
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent
        
    - name: 서비스 해제
      ansible.builtin.service:
        name: httpd
        state:  stopped
      
    - name: 방화벽 해제
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled