---
- name: 웹 서버 비활성화 및 삭제
  hosts: all
  gather_facts: false
  tasks:
    - name: 서비스 중지
      ansible.builtin.service:
        name: httpd
        state: stopped

    - name: 서비스 비활성화
      ansible.builtin.service:
        name: httpd
        enabled: false

    - name: 방화벽에서 HTTP 서비스 제거
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: disabled

    - name: 방화벽 재시작
      ansible.posix.firewalld:
        state: reloaded

    - name: httpd 패키지 삭제
      ansible.builtin.dnf:
        name: httpd
        state: absent

    - name: HTML 파일 삭제
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent
