# ---
# - name: 모든 관리 대상 호스트 전원 끄기
#   hosts: all
#   tasks:
#     - name: 전원 끄기
#       community.general.shutdown:
#         delay: 0
#       ignore_errors: true

- name: 제어 노드 전원 끄기
  hosts: localhost
  tasks:
    - name: 전원 끄기
      ansible.posix.at:
        command: shutdown -h now
        count: 1
        delay: 60
