---
# tasks file for myvhost
# 1) 패키지 설치 - httpd
# 2) 서비스 기동 - httpd.service 
# 3) 설정 파일-/etc/httpd/conf.d/vhost.conf => notify 
# 4) 방화벽 등록 - http
- name: 패키지 설치 
  ansible.builtin.dnf:
    name: httpd
    state: latest
- name: 서비스 기동
  ansible.builtin.service:
    name: httpd
    state: restarted
    enabled: true
- name: 디렉토리 생성
  ansible.builtin.file:
    path: "/var/www/{{ ansible_hostname }}"
    state: directory

- name: 설정 파일
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart_httpd

- name: 방화벽 등록
  ansible.builtin.firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled


    