---
- name: 사용자 추가
  hosts: devservers
  remote_user: devops
  become: true
  vars_files:
    - vars/secret.yml
  tasks: 
    - name: 사용자 추가 설정
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.pw | password_hash('sha512') }}"
      with_items:
        - { name: demouser1, pw: 'soldesk1.' }
        - { name: demouser2, pw: 'soldesk1.' }
