---
- name: Restore intranet services
  hosts: web1.example.com
  become: true
  tasks:
    - name: Disable httpd service
      service:
        name: httpd
        state: stopped
        enabled: false

    - name: Remove index.html file
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Remove httpd package
      yum:
        name: httpd
        state: absent

    - name: Remove http service from firewalld
      firewalld:
        service: http
        state: disabled
        permanent: true
      notify:
        - Reload firewalld

  handlers:
    - name: Reload firewalld
      firewalld:
        state: reloaded
