---
- name: 웹 서버 설정과 인증 페이지 구성
  hosts: all
  vars_files:
    - vars/vars.yml
  tasks:
    # 1) 패키지 설치 - firewalld, httpd, mod_ssl
    - name: 1) 패키지 삭제 - "{{ pkgs }}"
      ansible.builtin.yum:
        name: "{{ pkgs }}"
        state: absent

    # 2) /etc/httpd/conf/httpd.conf
    # 3) /var/www/html/.htaccess 생성
    # 4) /etc/httpd/secrets/ 생성
    # 5)_/etc/httpd/secrets/htpasswd 생성
    # 6) /var/www/html/index.html
    - name: 2-1) httpd.conf 파일 삭제
      ansible.builtin.file:
        path: "{{ conf_web_dst }}"  # 삭제할 파일 경로
        state: absent  # 파일 삭제

    - name: 2-2) .htaccess 파일 삭제
      ansible.builtin.file:
        path: "{{ htaccess_dst }}"  # 삭제할 파일 경로
        state: absent  # 파일 삭제

    - name: 2-3) /etc/httpd/secrets 디렉토리 삭제
      ansible.builtin.file:
        path: /etc/httpd/secrets
        state: absent  

    - name: 2-4) /etc/httpd/secrets/htpasswd 파일 삭제
      ansible.builtin.file:
        path: "{{ htpasswd_src }}"
        state: absent

    - name: 2-5) /var/www/html/index.html 삭제
      ansible.builtin.file:
        path: "{{ mainpage }}"
        state: absent 

    # 7) httpd, firewalld 서비스 기동
    - name: 3) 서비스 중단 - "{{ svcs }}"
      ansible.builtin.service:
       name: "{{ item }}"
       state: stopped  # 서비스 중단
       enabled: false  # 서비스 비활성화
      loop: "{{ svcs }}"  # svcs 리스트를 순회

    # 8) 방화벽 등록 - http, https
    - name: 4) 방화벽 포트 등록 해제 - "{{ fw_svcs }}"
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true  # 방화벽 설정을 영구적으로 변경
        immediate: true  # 즉시 적용
        state: disabled  # 서비스 비활성화
      loop: "{{ fw_svcs }}"  # fw_svcs 리스트를 순회