- name: Restore playbook.yml
  hosts: all
  tasks: 
    # 1) 방화벽 포트 닫기 - http, https
    - name: 방화벽 포트 닫기
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      loop:  # 'with_items' 대신 'loop' 사용
        - http
        - https

    # 2) 서비스 내리기 - firewalld, httpd
    - name: 서비스 내리기
      service:
        name: "{{ item }}"
        state: stopped
      loop:  # 'with_items' 대신 'loop' 사용
        - firewalld
        - httpd

    # 3) 웹서비스 설정 삭제
    - name: 웹서비스 설정 삭제
      file:
        path: /var/www/html/index.html
        state: absent

    # 4) 패키지 삭제 - httpd, firewalld
    - name: 패키지 삭제
      yum:
        name:
          - httpd
          - firewalld
        state: absent

    # 5) 사용자 정의 팩트 삭제 - /etc/ansible/facts.d/
    - name: 사용자 정의 팩트 삭제
      file:
        path: /etc/ansible/facts.d
        state: absent
        # state: absent는 디렉토리를 삭제하므로 주의가 필요함
        # 만약 디렉토리 내부의 파일만 삭제하고 싶다면, 아래와 같이 사용:
        # state: directory
        # state: absent
