- name: 웹페이지 확인
  hosts: "{{ myhost }}"
  become: false
  gather_facts: false
  tasks:
    - name: 웹서버의 메인 페이지 확인
      ansible.builtin.uri:
        url: "{{ myurl }}"
        status_code: 200
      register: result

    - name: 웹페이지 출력 확인
      ansible.builtin.debug:
        var: result.msg
